schema-version = "1.10.0"

[install]
claude-code.pkg-path = "flox/claude-code"
meson.pkg-path = "meson"
ninja.pkg-path = "ninja"
gcc.pkg-path = "gcc"
cctools.pkg-path = "cctools"
cctools.priority = 6
cctools.systems = [ "x86_64-darwin", "aarch64-darwin" ]
gperf.pkg-path = "gperf"
gperf.systems = [ "x86_64-linux", "aarch64-linux" ]

[build.systemd-portable]
description = "Portable adaptation of systemd for orchestrating services in user space"
version = "v260-rc2-81"
sandbox = "pure"
command = """
  oslc="$(uname | tr '[A-Z]' '[a-z]')"
  meson setup --reconfigure build-$oslc \
    --prefix=$out \
    -Dconfigfiledir=$out/etc \
    -Ddocdir=$out \
    -Dportable-manager=true

  # Build + install
  ninja -C build-$oslc install
"""
